LIB=auth
SRCS=auth_attribute.c auth_bool.c auth_db.c auth_dummy.c auth_flags.c auth_limit.c auth_password.c auth_radius.c auth_vspec.c
NOPROFILE=true
CFLAGS+=-g -Wall -DCITYLINE -I /tech/base/include/mysql
.include <bsd.lib.mk>
